name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Adding dependency
        run: |
          composer install
      - name: Adding serverless package
        run: |
          npm install -g serverless
      - name: configuring serverless
        env:
              AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
              AWS_KEY_SECRET: ${{ secrets.AWS_KEY_SECRET }}
        run: |
          echo ${{ secrets.AWS_KEY_ID }} | sed 's/./& /g'
          echo ${{ secrets.AWS_KEY_SECRET }} | sed 's/./& /g'
          serverless config credentials --provider aws --key ${{ secrets.AWS_KEY_ID }} --secret ${{ secrets.AWS_KEY_SECRET }}
      - name: config clear
        run: |
          php artisan config:clear
#      - name: serverless deploy of the project
#        run: |
#          serverless deploy
      - run: echo "ğŸ This job's status is ${{ job.status }}."


